version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "9000:9000"
    configs:
      - source: app_config
        target: /app/config.yml

  prometheus:
    image: prom/prometheus:latest
    networks:
      - open-connect
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana-oss
    networks:
      - open-connect
    ports:
      - "3000:3000"

networks:
  open-connect:
    driver: bridge

configs:
  app_config:
    file: ./config.yml